<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <ProjectReference Include="..\AgenticJobSearch.Application\AgenticJobSearch.Application.csproj" />
    <ProjectReference Include="..\AgenticJobSearch.Domain\AgenticJobSearch.Domain.csproj" />
    <ProjectReference Include="..\AgenticJobSearch.Infrastructure\AgenticJobSearch.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
